cd /var/jenkins_home/workspace/nodejs-helloworld/
cat << EOF > env.list
RDS_HOSTNAME=${RDS_HOSTNAME}
RDS_USERNAME=${RDS_USERNAME}
RDS_PASSWORD=${RDS_PASSWORD}
RDS_PORT=${RDS_PORT}
REDIS_HOSTNAME=${REDIS_HOSTNAME}
REDIS_PORT=${REDIS_PORT}
EOF